### PR TITLE
add support for zstd compression

### PR DESCRIPTION
**Pull request by hesmar**
## Description of the Change

This PR adds support for zstd compressed data tar archives.

## Checklist

- [ ] unit-test added (if change is algorithm)
- [ ] functional test added/updated (if change is functional)
- [ ] man page updated (if applicable)
- [ ] bash completion updated (if applicable)
- [ ] documentation updated
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by SteamedFish** [comment]
Debian is still using xz compression by default.

Ubuntu has switched to zstd by default since [dpkg 1.20.9ubuntu2](http://changelogs.ubuntu.com/changelogs/pool/main/d/dpkg/dpkg_1.20.9ubuntu2/changelog).

**Comment by lbolla** [comment]
@hesmar do you mind cleaning up the `go.sum`/`go.mod` files (which seems to include unneeded packages) and rebase against master?

**Comment by lbolla** [comment]
@hesmar Would you mind rebasing against master: we have GH Actions to run tests on CI.

Also, unittests are missing for this PR. They are needed for it to be considered for merging. Thanks!

**Comment by lbolla** [comment]
Actually, I'm deprecating this PR in favor of https://github.com/aptly-dev/aptly/pull/1002

**Pull request closed without merging**
