### PR TITLE
Snapshot Pull API

### PR DESCRIPTION
**Pull request by reglim**
## Description of the Change

- provide snapshot pull api
- use proper REST api for snapshot merge
  - **this breaks the existing snapshot merge  api, which is only available in CI builds**
- improve swagger doc

## Checklist

- [x] documentation updated
- [x] swagger documented

### CODE REVIEW

**Comment by neolynx** [comment]
codecov/patch is a bit log, but mainly due to a lot of error handling, I think this is acceptable

**Review by an0rak-dev — APPROVED** [review]

**Comment by neolynx** [comment]
@cfiehe I updated the swagger doc here, making it look nicer and actually work with the json body params...

2024-10-03-161524_4480x1440_scrot

**Comment by neolynx** [comment]
I discovered that `/snapshots/merge` and `/snapshots/pull` were not implemented as the other /api/snapshot/:name methods and as passing a To to Destination as json arguments. This change also fixes these APIs, leading to a backward incompatibility with the existing `/snapshots/merge`  in CI builds. I hope this does not cause too much troubles...

**Comment by an0rak-dev** [comment]
> This change also fixes these APIs, leading to a backward incompatibility with the existing `/snapshots/merge` in CI builds. I hope this does not cause too much troubles...

@neolynx Maybe we should tag somewhere (the Readme, a commit message, an issue...) that the next release containing this feature should be a major one since backward compatibility is broken with this ?

**Review by an0rak-dev — APPROVED** [review]

**Review by cfiehe — APPROVED** [review]
Looks good to me, but I must admit, that I am not familiar with using Swagger in Go.

**Pull request merged**
