### PR TITLE
increase buffers

### PR DESCRIPTION
**Pull request by strajansebastian**
Fixes #
In case there is a really long list of dependencies can't add the package to aptly.
Would be nice to have this configured via an option flag as a future improvement.

## Requirements

All new code should be covered with tests, documentation should be updated. CI should pass.

## Checklist

- [x] unit-test added (if change is algorithm)
- [x] functional test added/updated (if change is functional)
- [x] man page updated (if applicable)
- [x] bash completion updated (if applicable)
- [x] documentation updated
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by smira** [comment]
Do you have something to reproduce the failure? 

I think `bufio.Reader` buffer size is irrelevant, as it just controls buffering, while `bufio.Scanner` by default has max token size set at 64k which might be too low for your case?

**Comment by strajansebastian** [comment]
[aptly_dev_long_log.txt](https://github.com/aptly-dev/aptly/files/1995131/aptly_dev_long_log.txt)

I've uploaded the info for a big package that generates an error without a buffer increase.

**Comment by strajansebastian** [comment]
I made a local test with the latest release of aptly and you can see the error below:


root@test-aptly-latest:~# aptly repo add test-local project-pshark-core_20180503082509.master.34408_amd64.deb 
Loading packages...
[!] Unable to read file project-pshark-core_20180503082509.master.34408_amd64.deb: bufio.Scanner: token too long
[!] Some files were skipped due to errors:
  project-pshark-core_20180503082509.master.34408_amd64.deb



____________________________________________
EXTRA INFO:
root@test-aptly-latest:~# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

root@test-aptly-latest:~# dpkg --list | grep aptly
ii  aptly                               1.2.0                                      amd64        Debian repository management tool

**Comment by strajansebastian** [comment]
A rebuild for the aptly binary just with the 
_return &ControlFileReader{scanner: bufio.NewScanner(bufio.NewReaderSize(r, 10*1024*1024))}_ 
and it throws the same error:

**aptly repo add test-local project-pshark-core_20180503082509.master.34408_amd64.deb** 
_Loading packages...
[!] Unable to read file project-pshark-core_20180503082509.master.34408_amd64.deb: bufio.Scanner: token too long
[!] Some files were skipped due to errors:
  project-pshark-core_20180503082509.master.34408_amd64.deb
ERROR: some files failed to be added_

So that change may be useless.
However the other one seems to fix the issue on our side, but it seems that it breaks some tests 
_buf := make([]byte, 0, 65536)
c.scanner.Buffer(buf, 4194304)_

Here are the results of the tests from travis:
_PANIC: format_test.go:84: ControlFileSuite.TestReadStanza
**... Panic: Buffer called after Scan** (PC=0x458C28)
/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/panic.go:489
  in gopanic
/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/bufio/scan.go:258
  in Scanner.Buffer
format.go:227
  in ControlFileReader.ReadStanza
format_test.go:90
  in ControlFileSuite.TestReadStanza
/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/reflect/value.go:302
  in Value.Call
/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/asm_amd64.s:2197
  in goexit_



I think that the best option would be to increase the buffer somewhere before the return to avoid recalling the buffer after a scan was issued, how it happens in the current change:
_func NewControlFileReader(r io.Reader) *ControlFileReader {
	return &ControlFileReader{scanner: bufio.NewScanner(bufio.NewReaderSize(r, 32768))}
 }_

I'm not that familiar with go, what do you think that the best option would be to fix this (internally I can write something that will work somehow, but it would be nice to know that it is possible to upgrade aptly any time without breaking it if the patch is not reapplied)?

**Comment by smira** [comment]
Thank you, I've pushed some changes to #736, I think this one is good to be closed

**Pull request closed without merging**
