### PR TITLE
Allow to add a new component to a published repo

### LINKED ISSUE #832: Support adding a new component to an existing published repo
## Detailed Description
You currently cannot add a new component to an existing published repo. `aptly publish snapshot` will fail because the repo already exists and `aptly publish switch` will not allow to switch a non-existent component

## Context

This is useful when you figure out later on that you need another component for an existing repo.

## Your Environment

Aptly 1.2.0

### PR DESCRIPTION
**Pull request by cfiehe**
Fixes  #832, #1242

## Description of the Change

This commit modifies the behavior of the publish switch method in the way, that also new components can be added to an already published repository. It is no longer necessary to drop and recreate the whole publish.

## Checklist

- [ ] unit-test added (if change is algorithm)
- [ ] functional test added/updated (if change is functional)
- [ ] man page updated (if applicable)
- [ ] bash completion updated (if applicable)
- [ ] documentation updated
- [ ] author name in `AUTHORS`

### CODE REVIEW

**Comment by cfiehe** [comment]
recheck

**Comment by cfiehe** [comment]
I have no idea, why the test is failing. The corresponding component check has been removed.

**Comment by neolynx** [comment]
what a great feature to have :-) thanks a lot !

the feature/debian branch is moving to go 1.22, so I would merg this one afterwards...

**Review by neolynx — APPROVED** [review]
thanks !

**Comment by neolynx** [comment]
please rebase ! then we can merge...

**Comment by neolynx** [comment]
I rebased and force pushed to your branch...

**Comment by cfiehe** [comment]
@neolynx
Cool. Thank you very much for merging this pull request ❤️.

**Comment by neolynx** [comment]
See https://github.com/aptly-dev/aptly/discussions/1345 for the new APT repos containing a CI build with this change!

**Comment by cfiehe** [comment]
That are really great news 😃. Thank you very much for all your efforts spent so far for improving, fixing, enhancing and getting Aptly back to life.

**Pull request merged**
