### PR TITLE
[RFC] make binary packages optional

### LINKED ISSUE #758: not working with mirrors containing just sources (dsc)
If a mirror just contains source packages, aptly is not able to update it.

aptly always expects that there are binary packages on the mirror.

### PR DESCRIPTION
**Pull request by manut**
this would fix #758 

Signed-off-by: Manuel Traut <manut@linutronix.de>

### CODE REVIEW

**Comment by manut** [comment]
if this solution is basicly acceptable i would fixup the unit-tests, man-pages, etc. just let me know!

**Comment by sliverc** [comment]
In general the approach looks OK to me. @smira might have some more insights though.

**Comment by smira** [comment]
Looks good, except that I would probably invert the logic to `-skip-debs`.

But after cursory look - would it be sufficient to simply supply empty list of architectures?

**Comment by lbolla** [comment]
@neolynx @randombenj I would suggest we close this PR and just add a note in the documentation to say that if we want to work with source-only repos, users just specify no architectures.

Agree?

**Pull request closed without merging**
