### PR TITLE
Compatibility with GnuPG 1.x and 2.x, auto-detect GnuPG version

### LINKED ISSUE #657: Gpg 2.1 compatiblity
Hello,
I'm on Debian Stretch (gpg 2.1). I generated my gpg key so I have a .gnupg/pubring.kbx instead of .gnupg/pubring.gpg and .gnupg/secring.gpg. The gpg provider doesn't work but I can't get the internal provider to work.
`host:~$ aptly publish repo -batch -gpg-key=<blah> -passphrase-file="/data/aptly/.DoNotRemoveMandatoryForAptly" -gpg-provider=internal <name> <prefix>
opengpg: failure opening keyring '/data/aptly/.gnupg/pubring.gpg': open /data/aptly/.gnupg/pubring.gpg: no such file or directory
opengpg: failure opening keyring '/data/aptly/.gnupg/secring.gpg': open /data/aptly/.gnupg/secring.gpg: no such file or directory
ERROR: unable to initialize GPG signer: couldn't find key for key reference <blah>`

I tried to specify -secret-keyring with the kbx and it didn't work either:
`ERROR: unable to initialize GPG signer: error load secret keyring: openpgp: invalid data: tag byte does not have MSB set`

Am I doing something wrong or does it need a fix (I may submit a PR then)?
Thanks!

### LINKED ISSUE #699: Allow custom path for gpg
As `gpg2` is becoming default now, allow custom path/name for gpg1 binaries.

### LINKED ISSUE #741: Debian packaging for debian stretch
## Detailed Description
The aptly debian package is out-of-date and that is problematic for debian stretch.

## Possible Implementation
Make sure the debian package installs correctly on debian stretch.  It should depend on the gnupg1 and gpgv1 packages for Debian stretch (breaking change in aptly version 1.3.0).

Even after installing both packages, keys that worked before will not longer work after the upgrade to 1.3.0 (since keys would typically be generated with the default gpg version in stretch - it worked in 1.2.0, so this is a regression)

## Context
`ERROR: unable to initialize GPG signer: looks like there are no keys in gpg, please create one (official manual: http://www.gnupg.org/gph/en/manual.html)`

## Your Environment
Debian Stretch + Aptly 1.3.0 (upgrade from 1.2.0)

### PR DESCRIPTION
**Pull request by smira**
Fixes #741 
Fixes #699 
Fixes #657

## Requirements

aptly should support transparently GnuPG 1.x and 2.x via `gpg` PGP provider. Internal PGP provider only supports GnuPG 1.x keyring format (as openpgp Go library doesn't support GnuPG 2.1+ kerying format).

## Description of the Change

* aptly can sign and verify without issues with GnuPG 1.x and 2.x
* aptly auto-detects GnuPG version and adapts accordingly
* aptly automatically finds suitable GnuPG version

Majority of the work was to get unit-tests which can work with GnuPG 1.x & 2.x. Locally I've verified that aptly supports GnuPG 1.4.x & 2.2.x. Travis CI environment is based on trusty, so it runs gpg2 tests with GnuPG 2.0.x. 

Configuration parameter `gpgProvider` now supports three values for GnuPG:

* `gpg` (same as before, default): use GnuPG 1.x if available (checks `gpg`, `gpg1`), otherwise uses GnuPG 2.x; for aptly users who already have GnuPG 1.x environment (as it was the only supported version) nothing should change; new users might start with GnuPG 2.x if that's their installed version
* `gpg1` looks for GnuPG 1.x only, fails otherwise
* `gpg2` looks for GnuPG 2.x only, fails otherwise

## Checklist

- [x] unit-test added (if change is algorithm)
- [x] functional test added/updated (if change is functional)
- [x] man page updated (if applicable)
- [ ] bash completion updated (if applicable)
- [ ] documentation updated
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by smira** [comment]
There are some code coverage issues in `openpgp/internal.go`, I will get them sorted out tomorrow

**Comment by smira** [comment]
@sliverc good point, I will add detection of gpg1/2 to system tests and I will add tests on signing/verifying with gpg2

**Comment by smira** [comment]
@sliverc I've tried to address your feedback in 61e00b5

**Comment by bersace** [comment]
Kudo. Can't wait for next aptly release :-)

**Comment by iliis** [comment]
Not sure where to post this, but it took me ages to figure out why gpg signing wouldn't work. I always got the following error when trying to publish via the API:

```
Signing file 'Release' with gpg, please enter your passphrase when prompted:
gpg: signing failed: Inappropriate ioctl for device
gpg: signing failed: Inappropriate ioctl for device
[GIN] 2021/12/28 - 11:53:14 | 500 |   72.174473ms |   192.168.64.39 |  POST     /api/publish
Error #01: unable to publish: unable to detached sign file: exit status 2
```

I was calling the API like this:

```
curl -X POST -H 'Content-Type: application/json' --data '{"SourceKind": "local", "Sources": [{"Name": "foobarrepo"}], "Architectures": ["amd64"], "Distribution": "wheezy", "GpgKey": "****", "Passphrase": "****"}' http://myserver/api/publish/foobar
```

when instead I should have put the GPG signing parameters into a sub-field:

```
curl -X POST -H 'Content-Type: application/json' --data '{"SourceKind": "local", "Sources": [{"Name": "foobarrepo"}], "Architectures": ["amd64"], "Distribution": "wheezy", "Signing": {"GpgKey": "****", "Passphrase": "****"}}' http://myserver/api/publish/foobar
```

It would be very nice if the API gave an error for unknown/unexpected parameters.

**Pull request merged**
