### PR TITLE
Add support for flat repositories with no Release file.

### PR DESCRIPTION
**Pull request by ffrank**
In flat repositories, the Release file is supported, but not mandatory,
according to the specification here:

https://wiki.debian.org/RepositoryFormat#Flat_Repository_Format

An example for such a repository is the MapR ecosystem:

http://archive.mapr.com/releases/ecosystem-5.x/ubuntu/binary/

Before this patch, it was not possible to create a mirror of that
repository. The new behavior is to ignore the missing metadata, and
to implicitly disable checksum checks, since there are no checksums to check.

### CODE REVIEW

**Comment by jschwartz79** [comment]
Do you know if this change will allow aptly to work with http://archive.mapr.com/releases/ecosystem-5.x/ubuntu/ ?  

Also any plans to merge this soon?

**Comment by smira** [comment]
@jschwartz79 I didn't have a chance to look into that yet, but http://archive.mapr.com/releases/ecosystem-5.x/ubuntu/ looks more like regular repo. Just try putting literally apt-sources.list line to `aptly mirror create xxx` and see where it goes ;)

**Comment by apachelogger** [comment]
@ffrank are you still interested in working on this?

From a casual glance, this would benefit greatly from either a system or a unit test.

**Comment by ffrank** [comment]
Sure, I can see about adding some tests. Thanks for picking this up.

From experience, unpatched aptly will not play well with the MapR repositories (or, at all).

**Comment by ffrank** [comment]
After rebasing, the patched code doesn't compile anymore (see Travis output). I can't seem to be able to make any sense of that error. Help?

**Comment by smira** [comment]
@ffrank this identifier was renamed to `http.Error` (https://github.com/aptly-dev/aptly/blob/master/http/http.go#L9)

**Comment by ffrank** [comment]
Thank you @smira. Missed the forest for all the trees.

Looks much better know. LMK if you feel those tests are inadequate or need refinement.

**Comment by ffrank** [comment]
Is the code coverage check a blocking issue?

**Comment by smira** [comment]
Code coverage decrease shouldn't be blocking for us, but I wonder if this new behavior is good - the test you modified for `suslik` is actually hitting a distribution which doesn't exist at all.  So it's not expected that `aptly mirror create` should succeed. I think we might at least try to `HEAD` `Packages` file to make sure it's there?

And probably we need some system test with flat repository which does `mirror update` to make sure there's no regression for flat repositories in the future.

**Comment by ffrank** [comment]
Very good points. Not quite sure how that test should look right now, but it will probably become clear once I sit down and try.

As for checking the Packages file, I looked for an available function for making a HTTP HEAD call from the `http` package, but didn't find one. Should I just make one? (Or just use stdlib from `Fetch`, ignoring the downloader object?)

**Comment by smira** [comment]
@ffrank probably better adding HEAD method to the downloader, it shouldn't be that complicated as existing `Download` methods

**Pull request closed without merging**
