### PR TITLE
feat: Add etcd database support

### PR DESCRIPTION
**Pull request by hudeng-go**
improve concurrent access and high availability of aptly with the help of the characteristics of etcd

## Requirements

All new code should be covered with tests, documentation should be updated. CI should pass.

## Checklist

- [x] unit-test added (if change is algorithm)
- [x] functional test added/updated (if change is functional)
- [x] man page updated (if applicable)
- [x] bash completion updated (if applicable)
- [x] documentation updated
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by lbolla** [comment]
@hudeng-go Thanks for the PR! Having different backends for aptly, besides leveldb, is an interesting idea, but one not to be taken lightly.

The PR, as it is, is a prototype: there are no tests or a use-case demonstrating the need for it. Or even a study showing how (and if) etcd would make aptly more reliable as claimed in the PR.

If you care pursuing this PR, let's discuss. Otherwise, I'll close it.

**Comment by hudeng-go** [comment]
The use of etcd comes from our own needs, mainly to facilitate the simultaneous access of HTTP API services and command-line tools in the warehouse. Therefore, we have selected the etcd database to facilitate the implementation of this demand, which has been used in our own production environment.

**Comment by r4co0n** [comment]
@hudeng-go , would you and the people using this patch be willing to contribute the relevant unit tests and documentation, so this can be confidently merged into mainline aptly? I think it would be quite sad if this just died waiting for compliance, but there is still quite some work to be done. But don't worry, the code is the hard part, the rest is just a chore. :)

**Comment by lbolla** [comment]
@hudeng-go What are your thought on this? Can I close it, or will you be able to work on unittests and docs?

**Comment by hudeng-go** [comment]
> @hudeng-go What are your thought on this? Can I close it, or will you be able to work on unittests and docs?

Sorry to put it off until now. I'll fill in the information next week.

**Comment by lbolla** [comment]
@hudeng-go This PR has gone stale. Are you willing to continue working on it? aptly-dev master branch now has GH Actions setup for CI tests. Would you mind rebasing against master so tests are run?

From looking at the PR, it seems like your tests require an `etcd` server running? How do you plan to do it automatically on the CI?

**Pull request closed without merging**
