### PR TITLE
Initial commit for GCS storage backend

### LINKED ISSUE #136: Add GCS backend
Hello,

Would that be possible to add a Google Cloud Storage backend for aptly ?
Here is the API : https://cloud.google.com/storage/docs/json_api/v1/?hl=FR
It seems to have a go library : https://cloud.google.com/storage/docs/json_api/v1/json-api-go-samples?hl=FR

Thoughts ?

### PR DESCRIPTION
**Pull request by ceocoder**
```
* missing system tests and unit tests
* gcs json lib doesn't have "test server" built it, which makes
  testing this kinda tricky
* a system test "CreateConfigTest" is failing ATM.
```

Fixes #136

### CODE REVIEW

**Comment by ceocoder** [comment]
@smira looks like the build is failing because Gomfile is missing some deps - is there a `gom update` command?

**Comment by smira** [comment]
@ceocoder I don't see any changes to `Gomfile` in this PR

It should include all new libraries which are used (including transitive dependencies)

Running `make install` should tell you the same errors

**Comment by blueandgold** [comment]
Is this PR still active?  I would love to use this.

**Comment by apachelogger** [comment]
@ceocoder are you still working on this or is it abandoned?

**Comment by smira** [comment]
Closing this PR as it looks to be abandoned.

**Comment by smstone** [comment]
Hey,

I was able to get Aptly to publish a repo via `S3PublishEndpoints` to a GCS bucket using the Interoperability API Google provides. In the Google Console, it is located in Storage -> Settings -> Interoperability tab.

After creating a Google Service Account, generating HMAC keys, and setting the IAM Storage Object Admin role on the bucket, I was able to publish a repo with the following example `S3PublishEndpoints` in the Aptly config:

```
"S3PublishEndpoints": {
  "test": {
    "region": "region-name",
    "bucket": "bucket-name",
    "endpoint": "https://storage.googleapis.com",
    "awsAccessKeyID": "hmac-access-key",
    "awsSecretAccessKey": "hmac-secret",
    "debug": true,
    "acl": " "
  }
},
```

One issue I encountered when setting it up was the `acl` config option defaults to `private` if not set in your config: https://github.com/aptly-dev/aptly/blob/24a027194ea8818307083396edb76565f41acc92/s3/public.go#L50-L52 however the Interoperability API was responding with a 400 Bad Request when `acl: private` was sent, as object policies are disable for my bucket:

```
<Error><Code>InvalidArgument</Code><Message>Invalid argument.</Message><Details>Cannot use ACL API to set object policy when object policies are disabled.</Details></Error>
```

I was able to get around this by setting the config option to `"acl": " "`, but was only able to discover this by switching the debug logging from `aws.LogDebug`: https://github.com/aptly-dev/aptly/blob/24a027194ea8818307083396edb76565f41acc92/s3/public.go#L96 to `aws.LogDebugWithHTTPBody` [1] which displays the response body and corresponding reasoning for the 400 Bad Request.

Anyway, hope this helps someone and thanks for the great project.

[1] https://github.com/aws/aws-sdk-go/blob/ca891573c00a9c7a41d41efcc5d3d8614e2f119c/aws/logger.go#L60-L64

**Pull request closed without merging**
