### PR TITLE
Feature/heatlh readiness probe

### LINKED ISSUE #1133: Liveness and Readiness Probe Endpoints
## Detailed Description

It would be nice to have `/ready` and `/healthy` endpoints like described in https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ for those who deploy to k8s

### PR DESCRIPTION
**Pull request by mmianl**
Fixes #1133

## Requirements

All new code should be covered with tests, documentation should be updated. CI should pass.

## Checklist

- [x] unit-test added (if change is algorithm)
- [x] functional test added/updated (if change is functional)
- [ ] man page updated (if applicable)
- [ ] bash completion updated (if applicable)
- [x] documentation updated
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by mmianl** [comment]
Hi,
What do you think of this change?

**Comment by randombenj** [comment]
I definitly like the change! As the `\n` in the version seems to make some problems, what do you think of instead of stripping the newlines in the code (https://github.com/aptly-dev/aptly/pull/1135/files#diff-bf98d5fab5bcfabded9769069e7318683f549ec91cff84c5f87a9ae3a3ca3d8dR28)
We change this in the Makefile: https://github.com/aptly-dev/aptly/blob/master/Makefile#L3

From `VERSION=$(shell echo $(TAG) | sed 's@^v@@' | sed 's@-@+@g')` to `VERSION=$(shell echo $(TAG) | sed 's@^v@@' | sed 's@-@+@g' | tr -d '\n)`

**Comment by mmianl** [comment]
Stripping the newline in the Makefile directly sounds like the better choice to me. I'll update this PR shortly...

**Comment by mmianl** [comment]
Makefile is now changed as suggested and all strings.Trim() calls are removed again.

**Review by randombenj — APPROVED** [review]

**Pull request merged**
