### PR TITLE
Feature/description

### PR DESCRIPTION
**Pull request by kkupciunas**
Currently, **Description** field in published repository Release files is a hardcoded string "_Generated by aptly_" - allow specifying custom description when publishing by specifying command line option
`-description`

### CODE REVIEW

**Comment by apachelogger** [comment]
It would be lovely if you could rebase this on master. It may also benefit from a system test.

**Comment by brennerm** [comment]
What's the issue preventing this from being merged?

**Comment by smira** [comment]
@brennerm system test would be really nice

**Comment by dlitz** [comment]
It would be good if we could customize _any_ field in the Release file, not just the specific ones anticipated by the aptly developer.  For example, I'd like to make a backports-style repo, which would mean adding `NotAutomatic: yes` and `ButAutomaticUpgrades: yes` to the Release file.

**Pull request closed without merging**
