### PR TITLE
Add support for zst compression

### PR DESCRIPTION
**Pull request by mbearup**
Fixes #

## Requirements

All new code should be covered with tests, documentation should be updated. CI should pass.

## Description of the Change

Adds support for zst compression. This is just a re-attempt at PR #1002  since that one seems to be stalled.

## Checklist

- [ ] unit-test added (if change is algorithm)
- [ ] functional test added/updated (if change is functional)
- [ ] man page updated (if applicable)
- [ ] bash completion updated (if applicable)
- [ ] documentation updated
- [ ] author name in `AUTHORS`

### CODE REVIEW

**Review by jasonzio — APPROVED** [review]

**Comment by randombenj** [comment]
Thanks for this change! Could you drop support for 1.14 as with the new package some checks seem to fail

**Comment by mbearup** [comment]
Removed 1.14 from ci.yml. Let me know if anything else I should change. Looks like CI re-run needs to be approved as well.

**Comment by randombenj** [comment]
@mbearup Thanks for the changes, could you please add a unit test for this change? Something similar to https://github.com/aptly-dev/aptly/blob/master/deb/deb_test.go#L42

**Comment by NeroBurner** [comment]
Like in https://github.com/aptly-dev/aptly/pull/658 we can use http://ddebs.ubuntu.com/pool/universe/q/qtbase-opensource-src/libqt5concurrent5-dbgsym_5.15.2+dfsg-12_amd64.ddeb as test file for the new unit tests as it is zstd compressed

This is the official Ubuntu 21.10 impish ddeb file listed in http://ddebs.ubuntu.com/dists/impish/universe/binary-amd64/Packages for the package `libqt5concurrent5-dbgsym`

**Comment by NeroBurner** [comment]
created a commit https://github.com/NeroBurner/aptly/commit/12b829dbeac0aaab7e5f9aa6adedbe71b8c39df3
https://github.com/NeroBurner/aptly/tree/zstd_compression

feel free to cherry-pick/squash-merge

```sh
git remote add neroburner https://github.com/NeroBurner/aptly.git
git fetch neroburner zstd_compression
git cherry-pick neroburner/zstd_compression
```

or I can open a PR as well, anything that helps :)

**Review by randombenj — APPROVED** [review]
Thanks for the changes @mbearup and the original changes from @ahaswell
and for the test @NeroBurner.

**Pull request merged**
