### PR TITLE
Add metrics endpoint with http metrics using Prometheus client lib

### LINKED ISSUE #408: Feature Request: Expose Metrics
in order to better monitor aptly , should it have a way of exposing metrics about itself. at say a /metrics endpoint. 

https://godoc.org/github.com/prometheus/client_golang/prometheus is a good candidate. 

what do you think?

### PR DESCRIPTION
**Pull request by mmianl**
Fixes #408

## Requirements
Enable basic Prometheus compatible instrumentation capabilities

## Description of the Change
Add metrics endpoint with basic http and go related metrics when running `api serve` which can be enabled or disabled by a switch in the config file (= `enableMetricsEndpoint`)

## Checklist
- [ ] unit-test added (if change is algorithm)
- [x] functional test added/updated (if change is functional)
- [ ] man page updated (if applicable)
- [ ] bash completion updated (if applicable)
- [x] documentation updated
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by mmianl** [comment]
Hello there,
what do you think of this change? The metrics endpoint can now be enabled or disabled by config file.

**Comment by randombenj** [comment]
Hi @mmianl 
Thanks a lot for the changes! Do you think you could add some simple tests to verify the functionality?

**Comment by mmianl** [comment]
Hi @randombenj 
Yes, I can certainly take a look at functional tests, I don't think that unit tests make a lot of sense, what do you reckon?

**Comment by mmianl** [comment]
Hello @randombenj,
Do you think this can be merged now?

**Review by randombenj — APPROVED** [review]
LGTM

**Pull request merged**
