### PR TITLE
Enable the ability to set a custom Codename when publishing

### PR DESCRIPTION
**Pull request by smstone**
## Description of the Change
This change will allow users to set a custom `Codename` in the release files when publishing.

This PR is inspired/guided by https://github.com/aptly-dev/aptly/pull/874 

Why this change is important?

While testing out Aptly, our test `apt-get` clients were exiting with non-zero status since `Codename` was changed in the release files that are baked out by Aptly:
```
E: Repository 'http://debianrepo.example.com/bionic unstable InRelease' changed its 'Codename' value from '' to 'unstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```

I attempted to update system tests / man pages, apologies if something was missed. I can also split these out into separate commits, if that is preferable.

## Checklist

- [ ] unit-test added (if change is algorithm)
- [x] functional test added/updated (if change is functional)
- [x] man page updated (if applicable)
- [x] bash completion updated (if applicable)
- [ ] documentation updated
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by smstone** [comment]
Hello @smira, is it possible to get this reviewed? Thanks for your time.

**Comment by mattmceuen** [comment]
I wanted to bump this - we are having the same issue.  This pull request resolves it; is it possible to get this merged @smira ?

**Review by lbolla — APPROVED** [review]
It looks good to me.

**Review by randombenj — APPROVED** [review]
Looks good to me!

@smstone if you are still interested in this change, would you mind rebasing and have a look at why the tests are failing now that we moved the new github actions pipeline :tada:

**Comment by randombenj** [comment]
I will close this as there seems to be a lack of interest for this change, feel free to leave a comment if you want this reopened

**Pull request closed without merging**
